# Generated by Django 5.2 on 2025-04-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='evento_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
