# Generated by Django 5.2 on 2025-05-03 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_notificacion_leida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='enviada',
        ),
    ]
