# Generated by Django 5.2 on 2025-05-03 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0006_remove_notificacion_enviada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='enviada_en',
        ),
    ]
