# Generated by Django 5.2 on 2025-05-03 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_skin_perfilusuario_reportepuntos_skinusuario'),
        ('tareas', '0007_remove_notificacion_enviada_en'),
    ]

    operations = [
    ]
