# Generated by Django 5.2 on 2025-05-05 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0008_merge_20250503_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='skin_activa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tareas.skin'),
        ),
    ]
